### 
//GET all freight options

GET http://localhost:3002/api/freight
Content-Type: : application/json

###

POST http://localhost:3002/api/freight
Content-Type: application/json

{
  "shipmentCompany": "DHL",
  "orderId": "9876",
  "deliveryDate": "200615",
  "price": "1234"
}

###

DELETE http://localhost:3002/api/freight/5ec415d04e043e49782a7f4d