### 
//GET all freight options

GET http://localhost:3002/api/freight
Content-Type: : application/json

###
// POST ner freight option

POST http://localhost:3002/api/freight
Content-Type: application/json

{
  "shipmentCompany": "DHL",
  "deliveryDate": "24",
  "shippingCost": "7"
}

###
// UPDATE current freight option

PUT http://localhost:3002/api/freight/5ecba494bdca5f1ae62a9376
Content-Type: application/json

{
  "shipmentCompany": "Uppdaterad frakt",
  "orderId": "1368",
  "deliveryDate": "snarast",
  "price": "00"
}

###

DELETE http://localhost:3002/api/freight/5ecbb940c605c02531ca954c