### 
//GET all freight options

GET http://localhost:3002/api/freight
Content-Type: : application/json

###

POST http://localhost:3002/api/freight
Content-Type: application/json

{
  "shipmentCompany": "Skriv nytt fraktalternativ här",
  "orderId": "1111",
  "deliveryDate": "000000",
  "price": "00"
}

###

DELETE http://localhost:3002/api/freight/5ec4c4b37550e658456d225f