GET http://localhost:3002/

###

POST http://localhost:3002/upload
Content-Type: multipart/form-data; boundary=FormDataRow

--FormDataRow
Content-Disposition: form-data; name="image"; filename="brown-brim.png"
Content-Type: image/png

< ./brown-brim.png
--FormDataRow--

### Tänk på följande:
### ALLA boundary's måste BÖRJA med --
### SISTA boundary'n måste AVSLUTAS med --