
//ONE
GET http://localhost:3002/api/images/5eda0979dbdafcf86a40afa7

###

POST http://localhost:3002/api/images
Content-Type: multipart/form-data; boundary=FormDataRow

--FormDataRow
Content-Disposition: form-data; name="image"; filename="brown-brim.jpg"
Content-Type: image/jpg

< ./brown-brim.jpg
--FormDataRow--

### Tänk på följande:
### ALLA boundary's måste BÖRJA med --
### SISTA boundary'n måste AVSLUTAS med --