// ----- ODER ------ // 
###
// GET ONE ORDER BY ID. 
GET http://localhost:3002/api/order/5ecbabd42d66c51f0f9cf74b

###
// GET ALL ORDERS. 
GET http://localhost:3002/api/order

###
// CREATE A ORDER. 
POST http://localhost:3002/api/neworder
Content-Type: application/json

{
  "userId": "176g3h7yb",
  "productId": ["ljh3833", "6hjhvjws"],
  "freightId": "13",
  "paymentMethod": "hats",
  "activeOrder": true
}

###
// DELETE ORDER
DELETE http://localhost:3002/api/order/5ec4cf387fc96805d8281c84

###
// UPDATE ORDER
PUT   http://localhost:3002/api/order/5ec4cbf51cd1905c28458b79
Content-Type: application/json

{
  "userId": "newId86733",
  "productId": ["newljh3833"],
  "freightId": "15",
  "paymentMethod": "visa",
  "activeOrder": true
}