// ----- PRODUCTS ------ // 
###
// GET ONE PRODUCT BY ID. 
GET http://localhost:3002/api/product/5ec58257ddd9dde2cba0693e

###
// GET ALL PRODUCTS. 
GET http://localhost:3002/api/product

###
// CREATE A NEW PRODUCT. 
POST http://localhost:3002/api/newproduct
Content-Type: application/json

{
  "name": "Blue Beanie",
  "imageUrl": "https://i.ibb.co/ypkgK0X/blue-beanie.png",
  "price": 18,
  "category": "hats",
  "season": "vinter",
  "size": "small",
  "quantity": 99,
  "description": "Vintrig go hatt. Perfekt för fjällpromenader."
}

###
// DELETE PRODUCT
DELETE http://localhost:3002/api/product/5ec3c7c41201c80fe7f5e022

###
// UPDATE PRODUCT
PUT   http://localhost:3002/api/product/5ec529876059d4d3fe4d9722
Content-Type: application/json

{
  "name": "Brown Brim",
  "imageUrl": "https://i.ibb.co/ZYW3VTp/brown-brim.png",
  "price": 25,
  "category": "hats",
  "season": "höst",
  "size": "small",
  "quantity": 99,
  "description": "Höstig go hatt. Perfekt för skogspromenader."
}