// ----- PRODUCTS ------ // 
###
// GET ONE PRODUCT BY ID. 
GET http://localhost:3002/api/product/5ec7853e1f3a4e16bcf55bea

###
// GET ALL PRODUCTS. 
GET http://localhost:3002/api/product

###
// CREATE A NEW PRODUCT. 
POST http://localhost:3002/api/newproduct
Content-Type: application/json

{
  "name": "Burgundy T-shirt",
  "image": "5ede93693aaed446464f5cd0",
  "price": 25,
  "category": ["Mens", "All"],
  "season": ["vår", "sommar"],
  "inventory": {
    "small": 60,
    "medium": 40,
    "large": 15,
    "xlarge": 20
  },
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
}

###
// DELETE PRODUCT
DELETE http://localhost:3002/api/product/5ec3c7c41201c80fe7f5e022

###
// UPDATE PRODUCT
PUT   http://localhost:3002/api/product/5ecb7fc7160eb8556158611b
Content-Type: application/json

{
  "name": "Grey Jean Jacket",
  "imageUrl": "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
  "price": 90,
  "category": "Jackets",
  "season": ["vår", "sommar"],
  "inventory": {
    "small": 50,
    "medium": 50,
    "large": 92,
    "xlarge": 88
  },
  "description": "Jackan som får alla andra att vända sig om och vissla när du går förbi."
}